### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/gui#1]
initial launch: update as we go along

- [ ] add files
- [ ] remove zoom buttons (that's what keyboard is for for)
- [ ] remove position slider (that's what scrollbars are for)
- [ ] make anchored top part opaque (too distracting when semi transparent)
   - [ ] add info that says what this is (that links to AF user.js repo)
   - [ ] move version number here
- [ ] update colors to match TZP
   - [ ] split css out to a file?

bonus
- [ ] add ability to list all hyperlinks (to console.log?)
   - this is handy to check they still exist and/or we have finally removed all insecure ones (if possible)

**Comment by Thorin-Oakenpants** [comment]
@icpantsparti2 all yours

**Comment by Thorin-Oakenpants** [comment]
@icpantsparti2 just want to say that I feel like I've abandoned you, but please know that I'm grateful for your quick edits and keeping this up to date - all with no fuss

**Comment by Thorin-Oakenpants** [comment]
earthlng just fixed a typo I had in a tag, I had a closing `}` instead of a `]` - @icpantsparti2 

https://github.com/arkenfox/user.js/commit/6789dc7fefac5594d958a065463b4dc9d265c089 - IDK if you want to update for that

**Comment by Thorin-Oakenpants** [comment]
@icpantsparti2 don't you sleep? thanks for updating in a _timely_ fashion 😁
